# Generated by Django 2.0.9 on 2018-12-19 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_cost', models.IntegerField(verbose_name='offer_cost')),
                ('offer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='offer_date')),
                ('offer_bidder', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offer_bidder', to=settings.AUTH_USER_MODEL)),
                ('offer_seller', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offer_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_cost', models.IntegerField(verbose_name='sold_cost')),
                ('sold_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sold_date')),
                ('sold_buyer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sold_buyer', to=settings.AUTH_USER_MODEL)),
                ('sold_seller', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sold_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
