# Generated by Django 2.0.9 on 2018-12-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20181119_0936'),
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offer_product', to='product.Product'),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='sold_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to='product.Product'),
        ),
    ]
