# Generated by Django 2.0.9 on 2018-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=120, verbose_name='Product Name')),
                ('quantity', models.IntegerField(verbose_name='Product Quantity')),
                ('location', models.CharField(max_length=200)),
                ('bread_date', models.DateField(verbose_name='Bread Date')),
                ('harvest_date', models.DateField(verbose_name='Harvest Date')),
                ('product_content', models.TextField(verbose_name='Product Information')),
                ('create_date', models.DateTimeField(verbose_name='Create Date')),
                ('product_photo', models.ImageField(upload_to='', verbose_name='Product Photo')),
            ],
        ),
    ]
