# Generated by Django 2.0.9 on 2018-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181111_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Product Photo'),
        ),
    ]
