# Generated by Django 2.0.9 on 2018-11-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181111_2346'),
        ('product', '0002_product_created_date'),
    ]

    operations = [
    ]
