# Generated by Django 2.0.9 on 2018-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20181118_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to='product_image', verbose_name='Product Photo'),
        ),
    ]
