# Generated by Django 2.0.9 on 2018-11-18 19:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181118_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='product_image/'), upload_to='', verbose_name='Product Photo'),
        ),
    ]
