# Generated by Django 2.0.9 on 2018-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181118_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Product Photo'),
        ),
    ]
