# Generated by Django 2.0.9 on 2019-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, default='product_place_holder.png', upload_to='', verbose_name='Product Photo'),
        ),
    ]
