# Generated by Django 2.0.9 on 2018-12-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
