# Generated by Django 2.0.9 on 2018-12-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_is_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_end',
        ),
    ]
