# Generated by Django 2.0.9 on 2018-12-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auction_is_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
