# Generated by Django 2.0.9 on 2019-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_is_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='min_auction_time',
            field=models.IntegerField(verbose_name='Auction period of validity(min)'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='product_photo',
            field=models.ImageField(blank=True, default='product_place_holder.png', upload_to='', verbose_name='Product Photo'),
        ),
    ]
